name: Laravel SonarCloud Inspection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: Code Inspection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, ctype, json, tokenizer, xml, pdo, curl, dom, fileinfo, openssl
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install NPM dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=salmannhr_Basic_Java_maven-1302220122 \
            -Dsonar.organization=salmannhr \
            -Dsonar.sources=. \
            -Dsonar.exclusions=vendor/**,storage/**,node_modules/**,public/** \
            -Dsonar.php.coverage.reportPaths=storage/coverage.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
